# Generated by Django 4.2 on 2023-04-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='description',
        ),
    ]
