# Generated by Django 4.2 on 2023-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_userfavorite_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='query',
            field=models.CharField(default='', max_length=50),
        ),
    ]
