# Generated by Django 4.2 on 2023-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_newsarticle_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavorite',
            new_name='UserArticle',
        ),
        migrations.AlterModelTable(
            name='userarticle',
            table='user_articles',
        ),
    ]
