# Generated by Django 4.2 on 2023-04-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_rename_userfavorite_userarticle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='url',
            new_name='link',
        ),
    ]
