# Generated by Django 4.2 on 2023-04-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_rename_url_newsarticle_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='date',
            new_name='created_at',
        ),
    ]
