# Generated by Django 4.2 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_rename_date_userarticle_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='query',
            field=models.CharField(default='', max_length=50),
        ),
    ]
